### ISSUE TITLE
Fill up DESCRIPTION

### ISSUE THREAD

**Issue by pbiecek** [ModelOriented/modelDown#1]
Lots of missing information in DESCRIPTION
please update
Do you really need R in 3.5?
You can start with R 3.0 in the requirements

**Comment by Matiszak** [comment]
DESCRIPTION updated. Also minimum import versions were added to avoid any errors caused by invalid versions of dependencies.

**Comment by Matiszak** [comment]
Waiting for confirmation/any suggestions by @pbiecek
