### ISSUE TITLE
Error 'factor_columns[[i]]': index is out of range

### ISSUE THREAD

**Issue by mstaniak** [ModelOriented/modelDown#19]
example code

library(DALEX)
library(live)
library(modelDown)
proba <- e1071::svm(quality~.,data=wine)
modelDown(DALEX::explain(proba, data = wine, y = wine$quality))

output

[1] "Generating model_performance..."
[1] "Generating variable_importance..."
[1] "Generating variable_response..."
[1] "Generating prediction_breakdown..."
Błąd w poleceniu 'factor_columns[[i]]':indeks jest poza granicami

**Comment by mstaniak** [comment]
It worked after I added random factor variable
wine <- dplyr::mutate(wine, cat = as.factor(sample(letters, nrow(wine), TRUE)))
so that's were the problem came from

**Comment by Matiszak** [comment]
Thank you for submitting the issue, fix will be provided shortly.

**Comment by Matiszak** [comment]
Fixed.
