### ISSUE TITLE
Storing results

### ISSUE THREAD

**Issue by mstaniak** [ModelOriented/modelDown#20]
Are the results of computations stored in any way? For example, PDP takes some time to compute and it would be nice to have access to the results

**Comment by kromash** [comment]
Hello, there is no such feature yet but it's a nice idea. We could add option to save results of DALEX functions like `variable_response` to output folder and reuse it later during next generation of modelDown page or for further analysis by user.

**Comment by mstaniak** [comment]
Using them to speed up future calculations is a cool idea, perhaps archivist package could help keep track of what changed.

**Comment by pbiecek** [comment]
I've added copies of explainers (as R objects) to the modelDown website. 
Now there is a list of explainers with links marked as (download) and a directory called explainers in which models are stored as RDS files.
