### ISSUE TITLE
Add plot description

### ISSUE THREAD

**Issue by magda-tatarynowicz** [ModelOriented/modelDown#26]
Each plot (or plot type?) should also contain links to provide information on how to read the plot, what it presents, how it was generated:
- one link with business description
- one link with technical description (from DALEX package)

**Comment by Matiszak** [comment]
Business description source: e.g for model performance https://pbiecek.github.io/DALEX_docs/3-1-modelPerformance.html#modelPerformance
Technical description source: https://pbiecek.github.io/DALEX/

**Comment by Matiszak** [comment]
All descriptions implemented. Closed.
