### ISSUE TITLE
Session info

### ISSUE THREAD

**Issue by magda-tatarynowicz** [ModelOriented/modelDown#28]
Use archivist to save session state

In case of problem with archivist intergration, add link to R's sessionInfo (as text file)

**Comment by magda-tatarynowicz** [comment]
@pbiecek For which artifact should we use `asession()` to retrieve session state? Each explainer provided by  user?

**Comment by pbiecek** [comment]
Since all objects are generated in a single R session, then they should have same `session_info()`.
Therefore all `asession()` should results in a same list. So I think it does not matter which one will be used by a user.

**Comment by pbiecek** [comment]
Actually, maybe it would be better to add `Session` module that will print only the `session_info()`. This will be more straightforward that pointing to asessions.
If needed, asessions will be still available in the archivist repository.
