### ISSUE TITLE
Drifter package integration

### ISSUE THREAD

**Issue by magda-tatarynowicz** [ModelOriented/modelDown#30]
Display results of check_drift function (https://modeloriented.github.io/drifter/reference/check_drift.html)

Show them in new tab that replaces 'Prediction breakdown' tab. In case user doesn't provide additional model, tab should be hidden.

Enable passing additional model (models?) (as DALEX explainers or just models with data and y?) to modelDown function so that check_drift function can be used

**Comment by pbiecek** [comment]
@kromash where I can find an example how to use the `drifter` module?

**Comment by kromash** [comment]
On `dev` branch, drifter module was added to main example and it's available in help for modelDown function.

Also I updated test and it generates drifter section as well.

Example from test:
`modelDown::modelDown(explainer_ranger, list(explainer_glm1, explainer_glm2), output_folder = "modelDown_tmp")`

**Comment by pbiecek** [comment]
Great, thanks
