### ISSUE TITLE
Add auditor features

### ISSUE THREAD

**Issue by magda-tatarynowicz** [ModelOriented/modelDown#32]
Add results from auditor package to first tab

Model Ranking Plot as first plot.

Autocorrelation, LIFT chart, model correlation, ROC, RROC.

plotScaleLocation?

**Comment by pbiecek** [comment]
missing example for the auditor `module` in modelDown{modelDown}. How to add autiror plot to the modelDown website?

**Comment by kromash** [comment]
@pbiecek It not exactly a new module, but additional charts for main page. I made it optional and updated documentation.

**Comment by pbiecek** [comment]
Why it's not a new module?
It would be more consistent with others.

Also `height ` is set to 5 (fixed value), should it be liked with `width` or a separate parameter?

**Comment by kromash** [comment]
Well, I thought, that we firstly wanted to have auditor charts in main page (first tab). For me it would be way better to move it to separate tab, as other modules.

Yes, height should be parameterizable and I would add it for other modules too. Also I noticed that in this repo we don't have svg support yet, so I will move it from "modelDown2" project.
