### ISSUE TITLE
Add pkgdown website

### ISSUE THREAD

**Issue by pbiecek** [ModelOriented/modelDown#4]
For R packages you can automatically add pkgdown website with pkgdown package
Find some examples here: https://github.com/mi2-warsaw/MI2DataLab_Seminarium/tree/master/2017_11_28_pkgdown

**Comment by Matiszak** [comment]
Added, visible at https://htmlpreview.github.io/?https://raw.githubusercontent.com/kromash/modelDown/master/docs/index.html

Link is also available on github project page (Readme.md)
