### ISSUE TITLE
devtools::check() problems

### ISSUE THREAD

**Issue by magda-tatarynowicz** [ModelOriented/modelDown#55]
A.
Consider adding  importFrom("utils", "capture.output", "tail") - roxygen
B.
Undefined global functions or variables:    DEFAULT_DEVICE DEFAULT_FONT_SIZE
(from config.R file - should it be removed and variables moved to R script?)

**Comment by kromash** [comment]
A.
 Added importFrom

B.
 Removed config.r. Instead of that, all constant variables are set in .onLoad function

**Comment by pbiecek** [comment]
Thanks
