### ISSUE TITLE
Variable response order

### ISSUE THREAD

**Issue by magda-tatarynowicz** [ModelOriented/modelDown#57]
Variables in 'Variable Response' tab should be order from most to least important - as in output of variable importance.

What if we have many explainers? Which order should be used then?

**Comment by Matiszak** [comment]
@pbiecek I created pull request with sorting the variables based on their importance from the first given explainer. Please see if it is enough or if we should do it differently.

**Comment by pbiecek** [comment]
@Matiszak thanks, this is exactly what I was thinking about
