### ISSUE TITLE
Archivist link generation

### ISSUE THREAD

**Issue by magda-tatarynowicz** [ModelOriented/modelDown#60]
output_folder should be ignored, for example:
for parameters  
remote_repository_path = "MI2DataLab/modelDown_example/docs",
output_folder = "../modelDown_Titanic_example"

correct link: archivist::aread("MI2DataLab/modelDown_example/docs/repository/e617d10e1606257c56ba7d192c5b8fe0")

current link:
archivist::aread("MI2DataLab/modelDown_example/docs/../modelDown_Titanic_example/repository/e617d10e1606257c56ba7d192c5b8fe0")

**Comment by pbiecek** [comment]
Thanks
