### ISSUE TITLE
Template for pkgdown generation

### ISSUE THREAD

**Issue by magda-tatarynowicz** [ModelOriented/modelDown#61]
https://github.com/mi2-warsaw/MI2template

**Comment by Matiszak** [comment]
@pbiecek Should we adapt our templates to the provided one(just changes in html/css) (1) ? Or create mechanism similar to _pkgdown.yml (_modeldown.yml ?) to directly utilize the template in the provided repo (mostly R code to support this kind of flexibility) (2) ? Option (1) is achiveable, Option (2) seems quite complicated, it would take much longer.

**Comment by pbiecek** [comment]
@Matiszak whatever is easier, so I guess (1)
