### ISSUE TITLE
Add package to CRAN

### ISSUE THREAD

**Issue by magda-tatarynowicz** [ModelOriented/modelDown#62]

**Comment by pbiecek** [comment]
Let me know before you will send this package to cran,
I would like to first replace the breakDown with iBreakDown

**Comment by kromash** [comment]
Comments from reviewer:

> The LICENSE file is only needed if you have additional restrictions 
> which you have not? In that case omit the file and its reference in the 
> DESCRIPTION file.
> 
> Please do not write to the user filespace. If you
> really have to write out something, use tempdir() if the user is not
> asked and in examples.
> 
> \dontrun{} should be only used if the example really cannot be executed 
> (e.g. because of missing additional software, missing API keys, ...) by 
> the user. That's why wrapping examples in \dontrun{} adds the comment 
> ("# Not run:") as a warning for the user.
> Please unwrap the examples if they are executable in < 5 sec, or replace 
> \dontrun{} with \donttest{}. Ideally find toy examples that can be 
> regularly executed and checked.

**Comment by pbiecek** [comment]
@kromash do you need any help with these points?
The `tempdir()` can be used in examples as output dir
And a very simple model with just few modules can be used in examples

**Comment by kromash** [comment]
@pbiecek Thank you,

I will try to resolve these issues this week. I wonder if we should use `tempdir()` for all modelDown output. I think reviewer had problem with that we create folder (called `output` by default) in user filespace and write to it. 

Do you think we should use `tempdir()`, instead of creating new directory in user filespace, without asking user where and what we will write?

**Comment by pbiecek** [comment]
@kromash Great, thanks

I think that they want `tempdir()` in examples, as the `output_folder` argument.
So for example in the modelDown.R file you can add the third line:

```
modelDown::modelDown(explainer_ranger, 
                     list(explainer_glm1, explainer_glm2), 
                     output_folder = paste0(tempdir(), "/modelDown")) 
```

But if user sets output_folder in his local directory then it should be fine
I had similar problem with `archivist` package, but it would enough to add tempdir() in examples

**Comment by kromash** [comment]
Ok, thanks

I will add `tempdir()` only to examples

**Comment by kromash** [comment]
I fixed comments that were pointed out and resubmitted package to CRAN

**Comment by kromash** [comment]
modelDown was successfully published to CRAN. https://cran.r-project.org/web/packages/modelDown/index.html

**Comment by pbiecek** [comment]
@kromash Excellent !!!
